spring:
  application:
    name: consumer
server:
  port: 10010
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8800/eureka/ ## for docker
      defaultZone: http://register-server.spring-cloud.svc.cluster.local:8800/eureka/ ###for k8s

